name = "photo2calendar"
compatibility_date = "2024-01-01"
main = "dist/_worker.js"

[[d1_databases]]
binding = "DB"
database_name = "photo2calendar"
database_id = "84643a48-87d1-42fb-9443-922478aff6fe"

[site]
bucket = "./dist"
